### PR TITLE
Replace deprecated `include` by a `include_tasks`

### PR DESCRIPTION
**Pull request by devnix**

### CODE REVIEW

**Review by jperera — APPROVED** [review]

**Review by jperera — COMMENTED** [review]
Could you add the change to the CHANGELOG?

**Comment by devnix** [comment]
@jperera Done. I've also updated #41, and #29 is still merge pending!

**Comment by devnix** [comment]
Hm, the build is failing, there are some inconsistencies across Ansible versions, let's put this on WIP

**Comment by devnix** [comment]
It's fixed but maybe Travis is not able to finish the phase of compiling PHP:
image

**Review by xtianae7 — APPROVED** [review]

**Review by ablancolopez — APPROVED** [review]

**Review by MarioNv91 — APPROVED** [review]

**Pull request merged**
